name: daily_run_test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '56 14 * * *'

env:
  BASE_SCORE: test_a

jobs:
  vlm_test:
    if: ${{!cancelled()}}
    runs-on: [linux-a100]
    strategy:
      fail-fast: false
      matrix:
        model: [Qwen/Qwen2-VL-7B-Instruct,OpenGVLab/InternVL2_5-8B,lmms-lab/llava-onevision-qwen2-7b-si]
        dataset: ["MMBench_V11_MINI MMStar_MINI AI2D_MINI","OCRBench_MINI"]
    container:
      image: kkscilife/vlmevalkit_2:a100
      options: "--gpus=all --ipc=host -e https_proxy=$https_proxy -e http_proxy=$http_proxy --pull never"
      volumes:
        - /mnt/187:/mnt/187
    steps:
      - name: clone_repo
        uses: actions/checkout@v3
      - name: vlm_env
        run: |
          echo $https_proxy
          cd $GITHUB_WORKSPACE
          pip install -e .
      - name: evaluation_model
        run: |
          ln -s /mnt/187/${{matrix.model}} .
          if [[ "${{matrix.model}}" == "lmms-lab/llava-onevision-qwen2-7b-si" ]];then
              model_name="llava_onevision_qwen2_7b_si"
          else:
              model_name=$(echo ${{matrix.model}} | awk -F'/' '{print $2}')
          fi
          python run.py --dataset ${{matrix.dataset}} --model $model_name
      - name: check_result
        run: |
          echo $model_name
          #python .github/scripts/assert_score.py --result_dir ./outputs/
