name: daily_run_test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '56 14 * * *'

env:
  BASE_SCORE: test_a

jobs:
  vlm_test:
    if: ${{!cancelled()}}
    runs-on: [linux-a100]
    strategy:
      fail-fast: false
      matrix:
        model: [Qwen2-VL-7B-Instruct,InternVL2_5-8B,llava_onevision_qwen2_7b_si]
        dataset: ["MMBench_V11_MINI MMStar_MINI AI2D_MINI","OCRBench_MINI"]
    container:
      image: vlmevalkit_2:a100
      options: "--gpus=all --ipc=host -e https_proxy=$https_proxy -e http_proxy=$http_proxy --pull never"
      volumes:
        - /nvme/qa-caif-cicd/vlmevalkit_own_runner:/nvme/qa-caif-cicd/vlmevalkit_own_runner
        - /mnt/187:/mnt/187
    steps:
      - name: clone_repo
        uses: actions/checkout@v3
      - name: vlm_env
        run: |
          echo $GITHUB_WORKSPACE
          pwd
          echo $http_proxy
          echo $https_proxy
          cd $GITHUB_WORKSPACE
          pip install -e .
      - name: evaluation_model
        run: |
          pwd
          #python run.py --dataset ${{matrix.dataset}} --model ${{matrix.model}}
      - name: check_result
        run: |
          pwd
          #python .github/scripts/assert_score.py --result_dir ./outputs/
