name: lint

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: linux-a100
    steps:
      - name: info
        run: |
          docker images
          id
          echo $LD_LIBRARY_PATH
          export LD_LIBRARY_PATH=/home/qa-caif-cicd/anaconda3/lib:$LD_LIBRARY_PATH
      - uses: actions/checkout@v3
      - name: Install pre-commit hook
        run: |
          id
