name: lint

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: linux-a100
    steps:
      - name: info
        run: |
          docker images
          id
      - uses: actions/checkout@v3
      - name: Install pre-commit hook
        run: |
          id
