name: lint

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pre-commit hook
        run: |
          pip install pre-commit
          pre-commit install
          echo $HOME
      - name: Linting
        run: pre-commit run --all-files
